server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100
    connection-timeout: 20000


logging:
  level:
    com.rockwill: info
    org.springframework: warn


spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false


brand:
  languages: en,fr,pl,et,bn,id,uk,cs,kn,gl,pa,sv,pt,no,ar,ku,hr,fi,eu,vi,tr,sw,ja,is,lv,nl,de,fa,hi,it,hy,es,te,eo,ka,ru,uz,sl,ca,bg,hu,el,he,sr,ps,ne,kk,az,af,ms,la,ko,mk,mt,tl,ur,ta,si,ha,da,ga,ceb,fil,th
  domain: www.test-static.com  #品牌商申请的域名
  static-output: ./static-output  #静态文件生成目录，也是Nginx配置的静态目录
  scheduler-enable: true #定时任务开启
  cron: "0 0 0,12 * * ?"
  execute-on-start: true #启动时执行页面静态化
  execute-on-domain: www.test-static.com
  domain-list:
  secret: 4e7f1a9c2d8b3e6f5a0c1b2d9e8f7a6c

cdn:
  enabled: true
  prefix: "https://oss.iwone.cn"
  version: 1.1.1

google-tag:
  id: G-0HKGZJNMN6
  domains:
     www.rockwill.com: G-MB2YBKF1WG